version: '2'

networks:
   service_network:
     external:
       name: nginxproxynetwork

services:
  pyservice:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ga_service
    environment:
      - VIRTUAL_HOST=proservice.sd.di.huc.knaw.nl
    ports:
      - 80:5000
    volumes:
      - /home/robz/:/home
    networks:
      - service_network
