import json


class Store:

    def get_data(self):
        store = {"dataSets": [
            {
                "dataSet": "u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__jaikwil",
                "label": "Ja, ik wil!",
                "indexes": [
                    {"collection": "jaikwil_thes_bruidegom", "collection_id": "thes_Bruidegom", "label": "Bruidegom"},
                    {"collection": "jaikwil_rpp_occupation", "collection_id": "rpp_Occupation", "label": "Occupation"},
                    {"collection": "jaikwil_thes_eerdereman", "collection_id": "thes_EerdereMan",
                     "label": "EerdereMan"},
                    {"collection": "jaikwil_ns1_place", "collection_id": "ns1_Place", "label": "Place"},
                    {"collection": "jaikwil_thes_bruid", "collection_id": "thes_Bruid", "label": "Bruid"},
                    {"collection": "jaikwil_thes_persoonsreligie", "collection_id": "thes_Persoonsreligie",
                     "label": "Persoonsreligie"},
                    {"collection": "jaikwil_thes_herkomstlocatie", "collection_id": "thes_Herkomstlocatie",
                     "label": "Herkomstlocatie"},
                    {"collection": "jaikwil_skos_concept", "collection_id": "skos_Concept", "label": "Concept"},
                    {"collection": "jaikwil_pnv_personname", "collection_id": "pnv_PersonName", "label": "PersonName"},
                    {"collection": "jaikwil_rpp_location", "collection_id": "rpp_Location", "label": "Location"},
                    {"collection": "jaikwil_rpp_observation", "collection_id": "rpp_Observation",
                     "label": "Observation"},
                    {"collection": "jaikwil_thes_eerderevrouw", "collection_id": "thes_EerdereVrouw",
                     "label": "EerdereVrouw"},
                    {"collection": "jaikwil_rpp_indexdocument", "collection_id": "rpp_IndexDocument",
                     "label": "IndexDocument"},
                    {"collection": "jaikwil_ns1_occupation", "collection_id": "ns1_Occupation", "label": "Occupation"},
                    {"collection": "jaikwil_thes_ondertrouwregister", "collection_id": "thes_Ondertrouwregister",
                     "label": "Ondertrouwregister"},
                    {"collection": "jaikwil_thes_huwelijksestaat", "collection_id": "thes_Huwelijksestaat",
                     "label": "Huwelijksestaat"},
                    {"collection": "jaikwil_rpp_religion", "collection_id": "rpp_Religion", "label": "Religion"},
                    {"collection": "jaikwil_rpp_reconstruction", "collection_id": "rpp_Reconstruction",
                     "label": "Reconstruction"},
                    {"collection": "jaikwil_rpp_relation", "collection_id": "rpp_Relation", "label": "Relation"},
                    {"collection": "jaikwil_thes_relatieomschrijving", "collection_id": "thes_Relatieomschrijving",
                     "label": "Relatieomschrijving"},
                    {"collection": "jaikwil_thes_beroep", "collection_id": "thes_Beroep", "label": "Beroep"},
                    {"collection": "jaikwil_thes_getuige", "collection_id": "thes_Getuige", "label": "Getuige"},
                    {"collection": "jaikwil_rdfs_resource", "collection_id": "rdfs_Resource", "label": "Resource"},
                    {"collection": "jaikwil_thes_adresomschrijving", "collection_id": "thes_Adresomschrijving",
                     "label": "Adresomschrijving"},
                    {"collection": "jaikwil_rpp_person", "collection_id": "rpp_Person", "label": "Person"}
                ]
            },
            {
                "dataSet": "u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__notarissennetwerk",
                "label": "Notarissennetwerk",
                "indexes": [
                    {"collection": "notarissennetwerk_bio_divorce", "collection_id": "bio_Divorce", "label": "Divorce"},
                    {"collection": "notarissennetwerk_schema_postaladdress", "collection_id": "schema_PostalAddress",
                     "label": "PostalAddress"},
                    {"collection": "notarissennetwerk_schema_book", "collection_id": "schema_Book", "label": "Book"},
                    {"collection": "notarissennetwerk_sem_eventtype", "collection_id": "sem_EventType",
                     "label": "EventType"},
                    {"collection": "notarissennetwerk_schema_role", "collection_id": "schema_Role", "label": "Role"},
                    {"collection": "notarissennetwerk_bio_marriage", "collection_id": "bio_Marriage",
                     "label": "Marriage"},
                    {"collection": "notarissennetwerk_bio_burial", "collection_id": "bio_Burial", "label": "Burial"},
                    {"collection": "notarissennetwerk_schema_creativework", "collection_id": "schema_CreativeWork",
                     "label": "CreativeWork"},
                    {"collection": "notarissennetwerk_schema_occupation", "collection_id": "schema_Occupation",
                     "label": "Occupation"},
                    {"collection": "notarissennetwerk_bio_death", "collection_id": "bio_Death", "label": "Death"},
                    {"collection": "notarissennetwerk_bio_individualevent", "collection_id": "bio_IndividualEvent",
                     "label": "IndividualEvent"},
                    {"collection": "notarissennetwerk_schema_place", "collection_id": "schema_Place", "label": "Place"},
                    {"collection": "notarissennetwerk_schema_propertyvalue", "collection_id": "schema_PropertyValue",
                     "label": "PropertyValue"},
                    {"collection": "notarissennetwerk_schema_visualartwork", "collection_id": "schema_VisualArtwork",
                     "label": "VisualArtwork"},
                    {"collection": "notarissennetwerk_bio_baptism", "collection_id": "bio_Baptism", "label": "Baptism"},
                    {"collection": "notarissennetwerk_sem_event", "collection_id": "sem_Event", "label": "Event"},
                    {"collection": "notarissennetwerk_pnv_personname", "collection_id": "pnv_PersonName",
                     "label": "PersonName"},
                    {
                        "collection": "notarissennetwerk_https___data_goldenagents_org_datasets_saa_ontology_intendedmarriage",
                        "collection_id": "https___data_goldenagents_org_datasets_SAA_ontology_IntendedMarriage",
                        "label": "IntendedMarriage"},
                    {"collection": "notarissennetwerk_bio_resignation", "collection_id": "bio_Resignation",
                     "label": "Resignation"},
                    {"collection": "notarissennetwerk_schema_person", "collection_id": "schema_Person",
                     "label": "Person"},
                    {"collection": "notarissennetwerk_rdfs_resource", "collection_id": "rdfs_Resource",
                     "label": "Resource"},
                    {"collection": "notarissennetwerk_bio_birth", "collection_id": "bio_Birth", "label": "Birth"}
                ]
            },
            {
                "dataSet": "u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__rijksmuseum",
                "label": "Rijksmuseum",
                "indexes": [
                    {"collection": "rijksmuseum_http___www_openarchives_org_ore_terms_aggregation",
                     "collection_id": "http___www_openarchives_org_ore_terms_Aggregation", "label": "Aggregation"},
                    {"collection": "rijksmuseum_http___rdfs_org_ns_void_dataset",
                     "collection_id": "http___rdfs_org_ns_void_Dataset", "label": "Dataset"},
                    {"collection": "rijksmuseum_skos_concept", "collection_id": "skos_Concept", "label": "Concept"},
                    {"collection": "rijksmuseum_edm_place", "collection_id": "edm_Place", "label": "Place"},
                    {"collection": "rijksmuseum_edm_webresource", "collection_id": "edm_WebResource",
                     "label": "WebResource"},
                    {"collection": "rijksmuseum_edm_agent", "collection_id": "edm_Agent", "label": "Agent"},
                    {"collection": "rijksmuseum_edm_timespan", "collection_id": "edm_TimeSpan", "label": "TimeSpan"},
                    {"collection": "rijksmuseum_edm_providedcho", "collection_id": "edm_ProvidedCHO",
                     "label": "ProvidedCHO"},
                    {"collection": "rijksmuseum_rdfs_resource", "collection_id": "rdfs_Resource", "label": "Resource"}
                ]
            },
            {
                "dataSet": "u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__schrijverskabinet",
                "label": "Schrijverskabinet",
                "indexes": [
                    {"collection": "schrijverskabinet_schema_scholarlyarticle",
                     "collection_id": "schema_ScholarlyArticle", "label": "ScholarlyArticle"},
                    {"collection": "schrijverskabinet_schema_visualartwork", "collection_id": "schema_VisualArtwork",
                     "label": "VisualArtwork"},
                    {"collection": "schrijverskabinet_schema_creativework", "collection_id": "schema_CreativeWork",
                     "label": "CreativeWork"},
                    {"collection": "schrijverskabinet_schema_person", "collection_id": "schema_Person",
                     "label": "Person"},
                    {"collection": "schrijverskabinet_schema_place", "collection_id": "schema_Place", "label": "Place"},
                    {"collection": "schrijverskabinet_rdfs_resource", "collection_id": "rdfs_Resource",
                     "label": "Resource"},
                    {"collection": "schrijverskabinet_schema_publicationevent",
                     "collection_id": "schema_PublicationEvent", "label": "PublicationEvent"}
                ]
            },
            {
                "dataSet": "u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__corporatiestukken",
                "label": "Corporatiestukken",
                "indexes": [{
                    "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_raad",
                    "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Raad",
                    "label": "Raad"}, {
                    "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_regentes",
                    "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Regentes",
                    "label": "Regentes"}, {"collection": "corporatiestukken_voidplus_clusteringalgorithm",
                                           "collection_id": "voidPlus_ClusteringAlgorithm",
                                           "label": "ClusteringAlgorithm"}, {
                    "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_thesaurierextraordinaris",
                    "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_ThesaurierExtraordinaris",
                    "label": "ThesaurierExtraordinaris"},
                    {"collection": "corporatiestukken_voidplus_clusterset",
                     "collection_id": "voidPlus_Clusterset", "label": "Clusterset"},
                    {"collection": "corporatiestukken_oa_annotation", "collection_id": "oa_Annotation",
                     "label": "Annotation"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_boekhouder200stepenning",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Boekhouder200StePenning",
                        "label": "Boekhouder200StePenning"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_kolonelgeneraal",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_KolonelGeneraal",
                        "label": "KolonelGeneraal"},
                    {"collection": "corporatiestukken_ga_roletype", "collection_id": "ga_RoleType",
                     "label": "RoleType"}, {"collection": "corporatiestukken_voidplus_partitionformulation",
                                            "collection_id": "voidPlus_PartitionFormulation",
                                            "label": "PartitionFormulation"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_substituut_schoutextraordinaris",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Substituut_SchoutExtraordinaris",
                        "label": "SchoutExtraordinaris"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_kapitein",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Kapitein",
                        "label": "Kapitein"},
                    {"collection": "corporatiestukken_bio_death", "collection_id": "bio_Death",
                     "label": "Death"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_schepen",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Schepen",
                        "label": "Schepen"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_rekenmeester",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Rekenmeester",
                        "label": "Rekenmeester"},
                    {"collection": "corporatiestukken_voidplus_linksetformulation",
                     "collection_id": "voidPlus_LinksetFormulation", "label": "LinksetFormulation"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_commissarisbankvanlening",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_CommissarisBankVanLening",
                        "label": "CommissarisBankVanLening"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_commissariszeezaken",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_CommissarisZeezaken",
                        "label": "CommissarisZeezaken"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_majoor",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Majoor",
                        "label": "Majoor"},
                    {"collection": "corporatiestukken_pnv_personname", "collection_id": "pnv_PersonName",
                     "label": "PersonName"},
                    {"collection": "corporatiestukken_ga_born", "collection_id": "ga_Born", "label": "Born"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_weesmeester",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Weesmeester",
                        "label": "Weesmeester"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_commissaris",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Commissaris",
                        "label": "Commissaris"}, {"collection": "corporatiestukken_voidplus_classpartition",
                                                  "collection_id": "voidPlus_ClassPartition",
                                                  "label": "ClassPartition"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_schutterij",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Schutterij",
                        "label": "Schutterij"},
                    {"collection": "corporatiestukken_bio_marriage", "collection_id": "bio_Marriage",
                     "label": "Marriage"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_provoost",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Provoost",
                        "label": "Provoost"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_commissariswisselbank",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_CommissarisWisselbank",
                        "label": "CommissarisWisselbank"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_kapiteinluitenant",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_KapiteinLuitenant",
                        "label": "KapiteinLuitenant"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_commissariskleinezaken",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_CommissarisKleineZaken",
                        "label": "CommissarisKleineZaken"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_gedeputeerdeterstatengeneraal",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_GedeputeerdeTerStatenGeneraal",
                        "label": "GedeputeerdeTerStatenGeneraal"},
                    {"collection": "corporatiestukken_ga_person", "collection_id": "ga_Person",
                     "label": "Person"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_assurantiemeester",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Assurantiemeester",
                        "label": "Assurantiemeester"}, {"collection": "corporatiestukken_ga_creativeartifact",
                                                        "collection_id": "ga_CreativeArtifact",
                                                        "label": "CreativeArtifact"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_raadordinaris",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_RaadOrdinaris",
                        "label": "RaadOrdinaris"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_burgemeester",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Burgemeester",
                        "label": "Burgemeester"}, {"collection": "corporatiestukken_voidplus_lensoperator",
                                                   "collection_id": "voidPlus_LensOperator",
                                                   "label": "LensOperator"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_gecommitteerderaad",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_GecommitteerdeRaad",
                        "label": "GecommitteerdeRaad"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_kolonel",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Kolonel",
                        "label": "Kolonel"},
                    {"collection": "corporatiestukken_voidplus_cluster", "collection_id": "voidPlus_Cluster",
                     "label": "Cluster"}, {"collection": "corporatiestukken_voidplus_matchingalgorithm",
                                           "collection_id": "voidPlus_MatchingAlgorithm",
                                           "label": "MatchingAlgorithm"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_secretaris",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Secretaris",
                        "label": "Secretaris"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_sergeant",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Sergeant",
                        "label": "Sergeant"},
                    {"collection": "corporatiestukken_bio_birth", "collection_id": "bio_Birth",
                     "label": "Birth"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_pensionaris",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Pensionaris",
                        "label": "Pensionaris"}, {"collection": "corporatiestukken_voidplus_validation",
                                                  "collection_id": "voidPlus_Validation",
                                                  "label": "Validation"},
                    {"collection": "corporatiestukken_ga_event", "collection_id": "ga_Event", "label": "Event"},
                    {"collection": "corporatiestukken_voidplus_validationset",
                     "collection_id": "voidPlus_Validationset", "label": "Validationset"},
                    {"collection": "corporatiestukken_rdf_statement", "collection_id": "rdf_Statement",
                     "label": "Statement"},
                    {"collection": "corporatiestukken_rdfs_sequence", "collection_id": "rdfs_Sequence",
                     "label": "Sequence"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_raadteradmiraliteit",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_RaadTerAdmiraliteit",
                        "label": "RaadTerAdmiraliteit"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_oppercommissarisderwalen",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_OppercommissarisDerWalen",
                        "label": "OppercommissarisDerWalen"},
                    {"collection": "corporatiestukken_voidplus_lensformulation",
                     "collection_id": "voidPlus_LensFormulation", "label": "LensFormulation"},
                    {"collection": "corporatiestukken_voidplus_validationflag",
                     "collection_id": "voidPlus_ValidationFlag", "label": "ValidationFlag"},
                    {"collection": "corporatiestukken_voidplus_lens", "collection_id": "voidPlus_Lens",
                     "label": "Lens"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_commissarishuwelijksezaken",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_CommissarisHuwelijkseZaken",
                        "label": "CommissarisHuwelijkseZaken"},
                    {"collection": "corporatiestukken_voidplus_matchingmethod",
                     "collection_id": "voidPlus_MatchingMethod", "label": "MatchingMethod"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_onderschout",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Onderschout",
                        "label": "Onderschout"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_gedeputeerdetergeneraliteitsrekenkamer",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_GedeputeerdeTerGeneraliteitsRekenkamer",
                        "label": "GedeputeerdeTerGeneraliteitsRekenkamer"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_hoofdschout",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Hoofdschout",
                        "label": "Hoofdschout"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_doelen",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Doelen",
                        "label": "Doelen"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_kerkmeester",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Kerkmeester",
                        "label": "Kerkmeester"}, {"collection": "corporatiestukken_voidplus_resourceselection",
                                                  "collection_id": "voidPlus_ResourceSelection",
                                                  "label": "ResourceSelection"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_overmanwijnkopersgilde",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_OvermanWijnkopersgilde",
                        "label": "OvermanWijnkopersgilde"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_raadteradmiraliteitin_tnoorderkwartier",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_RaadTerAdmiraliteitIn_TNoorderkwartier",
                        "label": "TNoorderkwartier"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_kastelein",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Kastelein",
                        "label": "Kastelein"},
                    {"collection": "corporatiestukken_ga_bride", "collection_id": "ga_Bride", "label": "Bride"},
                    {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_administrativeorganization",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_AdministrativeOrganization",
                        "label": "AdministrativeOrganization"},
                    {"collection": "corporatiestukken_ga_organization", "collection_id": "ga_Organization",
                     "label": "Organization"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_overman",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Overman",
                        "label": "Overman"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_hopman",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Hopman",
                        "label": "Hopman"}, {"collection": "corporatiestukken_voidplus_propertypartition",
                                             "collection_id": "voidPlus_PropertyPartition",
                                             "label": "PropertyPartition"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_schout",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Schout",
                        "label": "Schout"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_gecommitteerdeterrekenkamerterauditievanhollandinhetzuiderkwartier",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_GecommitteerdeTerRekenkamerTerAuditieVanHollandInHetZuiderkwartier",
                        "label": "GecommitteerdeTerRekenkamerTerAuditieVanHollandInHetZuiderkwartier"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_commissarisdesolateboedelskamer",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_CommissarisDesolateBoedelskamer",
                        "label": "CommissarisDesolateBoedelskamer"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_unknown",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Unknown",
                        "label": "Unknown"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_luitenantkolonel",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_LuitenantKolonel",
                        "label": "LuitenantKolonel"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_regent",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Regent",
                        "label": "Regent"},
                    {"collection": "corporatiestukken_ga_groom", "collection_id": "ga_Groom", "label": "Groom"},
                    {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_secretariszeezaken",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_SecretarisZeezaken",
                        "label": "SecretarisZeezaken"},
                    {"collection": "corporatiestukken_void_dataset", "collection_id": "void_Dataset",
                     "label": "Dataset"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_secretaris_thesaurierextraordinaris",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Secretaris_ThesaurierExtraordinaris",
                        "label": "ThesaurierExtraordinaris"},
                    {"collection": "corporatiestukken_voidplus_linkset", "collection_id": "voidPlus_Linkset",
                     "label": "Linkset"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_commissaris100stepenning",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Commissaris100StePenning",
                        "label": "Commissaris100StePenning"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_thesaurierordinaris",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_ThesaurierOrdinaris",
                        "label": "ThesaurierOrdinaris"},
                    {"collection": "corporatiestukken_ga_deceased", "collection_id": "ga_Deceased",
                     "label": "Deceased"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_vaandrig",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Vaandrig",
                        "label": "Vaandrig"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_luitenant",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Luitenant",
                        "label": "Luitenant"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_tamboer",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_Tamboer",
                        "label": "Tamboer"}, {
                        "collection": "corporatiestukken_https___data_goldenagents_org_datasets_corporatiestukken_roletype_commissarisgrootenexcijs",
                        "collection_id": "https___data_goldenagents_org_datasets_corporatiestukken_roletype_CommissarisGrootenExcijs",
                        "label": "CommissarisGrootenExcijs"},
                    {"collection": "corporatiestukken_oa_fragmentselector",
                     "collection_id": "oa_FragmentSelector", "label": "FragmentSelector"},
                    {"collection": "corporatiestukken_rdfs_resource", "collection_id": "rdfs_Resource",
                     "label": "Resource"}]
            },
            {
                "dataSet": "u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__ecartico",
                "label": "ECARTICO",
                "indexes": [
                    {"collection": "ecartico_https___schema_org_book", "collection_id": "https___schema_org_Book",
                     "label": "Book"},
                    {"collection": "ecartico_https___schema_org_article", "collection_id": "https___schema_org_Article",
                     "label": "Article"},
                    {"collection": "ecartico_https___schema_org_role", "collection_id": "https___schema_org_Role",
                     "label": "Role"}, {"collection": "ecartico_https___schema_org_structuredvalue",
                                        "collection_id": "https___schema_org_StructuredValue",
                                        "label": "StructuredValue"},
                    {"collection": "ecartico_http___purl_org_vocab_bio_0_1_marriage",
                     "collection_id": "http___purl_org_vocab_bio_0_1_Marriage", "label": "Marriage"},
                    {"collection": "ecartico_https___schema_org_archiveorganization",
                     "collection_id": "https___schema_org_ArchiveOrganization", "label": "ArchiveOrganization"},
                    {"collection": "ecartico_https___schema_org_periodical",
                     "collection_id": "https___schema_org_Periodical", "label": "Periodical"},
                    {"collection": "ecartico_https___schema_org_publicationissue",
                     "collection_id": "https___schema_org_PublicationIssue", "label": "PublicationIssue"},
                    {"collection": "ecartico_https___schema_org_creativework",
                     "collection_id": "https___schema_org_CreativeWork", "label": "CreativeWork"},
                    {"collection": "ecartico_https___schema_org_occupation",
                     "collection_id": "https___schema_org_Occupation", "label": "Occupation"},
                    {"collection": "ecartico_https___schema_org_bookseries",
                     "collection_id": "https___schema_org_BookSeries", "label": "BookSeries"},
                    {"collection": "ecartico_rdf_alt", "collection_id": "rdf_Alt", "label": "Alt"},
                    {"collection": "ecartico_https___schema_org_place", "collection_id": "https___schema_org_Place",
                     "label": "Place"}, {"collection": "ecartico_https___schema_org_datafeeditem",
                                         "collection_id": "https___schema_org_DataFeedItem", "label": "DataFeedItem"},
                    {"collection": "ecartico_http___semanticweb_cs_vu_nl_2009_11_sem_time",
                     "collection_id": "http___semanticweb_cs_vu_nl_2009_11_sem_Time", "label": "Time"},
                    {"collection": "ecartico_http___rdfs_org_ns_void_dataset",
                     "collection_id": "http___rdfs_org_ns_void_Dataset", "label": "Dataset"},
                    {"collection": "ecartico_https___schema_org_organization",
                     "collection_id": "https___schema_org_Organization", "label": "Organization"},
                    {"collection": "ecartico_http___www_opengis_net_ont_sf_point",
                     "collection_id": "http___www_opengis_net_ont_sf_Point", "label": "Point"},
                    {"collection": "ecartico_https___schema_org_archivecomponent",
                     "collection_id": "https___schema_org_ArchiveComponent", "label": "ArchiveComponent"},
                    {"collection": "ecartico_https___schema_org_geocoordinates",
                     "collection_id": "https___schema_org_GeoCoordinates", "label": "GeoCoordinates"},
                    {"collection": "ecartico_https___w3id_org_pnv_personname",
                     "collection_id": "https___w3id_org_pnv_PersonName", "label": "PersonName"},
                    {"collection": "ecartico_https___schema_org_person", "collection_id": "https___schema_org_Person",
                     "label": "Person"}, {"collection": "ecartico_https___schema_org_publicationvolume",
                                          "collection_id": "https___schema_org_PublicationVolume",
                                          "label": "PublicationVolume"},
                    {"collection": "ecartico_rdfs_resource", "collection_id": "rdfs_Resource", "label": "Resource"},
                    {"collection": "ecartico_foaf_person", "collection_id": "foaf_Person", "label": "Person"}]
            },
            {
                "dataSet": "u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__onstage",
                "label": "Onstage",
                "indexes": [{"collection": "onstage_http___rdfs_org_ns_void_dataset",
                             "collection_id": "http___rdfs_org_ns_void_Dataset", "label": "Dataset"},
                            {"collection": "onstage_https___schema_org_theatreevent",
                             "collection_id": "https___schema_org_TheatreEvent", "label": "TheatreEvent"},
                            {"collection": "onstage_https___schema_org_creativework",
                             "collection_id": "https___schema_org_CreativeWork", "label": "CreativeWork"},
                            {"collection": "onstage_https___schema_org_monetaryamount",
                             "collection_id": "https___schema_org_MonetaryAmount", "label": "MonetaryAmount"},
                            {"collection": "onstage_https___schema_org_person",
                             "collection_id": "https___schema_org_Person", "label": "Person"},
                            {"collection": "onstage_https___schema_org_place",
                             "collection_id": "https___schema_org_Place", "label": "Place"},
                            {"collection": "onstage_rdfs_resource", "collection_id": "rdfs_Resource",
                             "label": "Resource"}]
            },
            {
                "dataSet": "u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__nta",
                "label": "NTA",
                "indexes": [{"collection": "nta_http___rdfs_org_ns_void_dataset",
                             "collection_id": "http___rdfs_org_ns_void_Dataset", "label": "Dataset"},
                            {"collection": "nta_schema_webpage", "collection_id": "schema_WebPage", "label": "WebPage"},
                            {"collection": "nta_schema_dataset", "collection_id": "schema_Dataset", "label": "Dataset"},
                            {"collection": "nta_schema_person", "collection_id": "schema_Person", "label": "Person"},
                            {"collection": "nta_rdfs_resource", "collection_id": "rdfs_Resource", "label": "Resource"}]
            },
            {
                "dataSet": "u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__ggd",
                "label": "Gelegenheidsgedichten",
                "indexes": [{"collection": "ggd_voidplus_validation", "collection_id": "voidPlus_Validation",
                             "label": "Validation"},
                            {"collection": "ggd_schema_book", "collection_id": "schema_Book", "label": "Book"},
                            {"collection": "ggd_sem_eventtype", "collection_id": "sem_EventType", "label": "EventType"},
                            {"collection": "ggd_schema_webpage", "collection_id": "schema_WebPage", "label": "WebPage"},
                            {"collection": "ggd_rdf_statement", "collection_id": "rdf_Statement", "label": "Statement"},
                            {"collection": "ggd_schema_role", "collection_id": "schema_Role", "label": "Role"},
                            {"collection": "ggd_schema_individualproduct", "collection_id": "schema_IndividualProduct",
                             "label": "IndividualProduct"},
                            {"collection": "ggd_schema_place", "collection_id": "schema_Place", "label": "Place"},
                            {"collection": "ggd_schema_propertyvalue", "collection_id": "schema_PropertyValue",
                             "label": "PropertyValue"},
                            {"collection": "ggd_schema_organization", "collection_id": "schema_Organization",
                             "label": "Organization"},
                            {"collection": "ggd_schema_archivecomponent", "collection_id": "schema_ArchiveComponent",
                             "label": "ArchiveComponent"},
                            {"collection": "ggd_sem_event", "collection_id": "sem_Event", "label": "Event"},
                            {"collection": "ggd_pnv_personname", "collection_id": "pnv_PersonName",
                             "label": "PersonName"},
                            {"collection": "ggd_sem_roletype", "collection_id": "sem_RoleType", "label": "RoleType"},
                            {"collection": "ggd_sem_role", "collection_id": "sem_Role", "label": "Role"},
                            {"collection": "ggd_schema_dataset", "collection_id": "schema_Dataset", "label": "Dataset"},
                            {"collection": "ggd_schema_person", "collection_id": "schema_Person", "label": "Person"},
                            {"collection": "ggd_schema_musiccomposition", "collection_id": "schema_MusicComposition",
                             "label": "MusicComposition"},
                            {"collection": "ggd_rdfs_resource", "collection_id": "rdfs_Resource", "label": "Resource"},
                            {"collection": "ggd_schema_publicationevent", "collection_id": "schema_PublicationEvent",
                             "label": "PublicationEvent"}, {"collection": "ggd_http___rdfs_org_ns_void_dataset",
                                                            "collection_id": "http___rdfs_org_ns_void_Dataset",
                                                            "label": "Dataset"}]
            },
            {
                "dataSet": "u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__bredius",
                "label": "Bredius",
                "indexes": [{"collection": "bredius_voidplus_validation", "collection_id": "voidPlus_Validation",
                             "label": "Validation"}, {"collection": "bredius_voidplus_clusteringalgorithm",
                                                      "collection_id": "voidPlus_ClusteringAlgorithm",
                                                      "label": "ClusteringAlgorithm"},
                            {"collection": "bredius_voidplus_validationset", "collection_id": "voidPlus_Validationset",
                             "label": "Validationset"},
                            {"collection": "bredius_voidplus_clusterset", "collection_id": "voidPlus_Clusterset",
                             "label": "Clusterset"},
                            {"collection": "bredius_rdfs_sequence", "collection_id": "rdfs_Sequence",
                             "label": "Sequence"},
                            {"collection": "bredius_schema_structuredvalue", "collection_id": "schema_StructuredValue",
                             "label": "StructuredValue"}, {"collection": "bredius_voidplus_partitionformulation",
                                                           "collection_id": "voidPlus_PartitionFormulation",
                                                           "label": "PartitionFormulation"},
                            {"collection": "bredius_schema_collection", "collection_id": "schema_Collection",
                             "label": "Collection"}, {"collection": "bredius_voidplus_validationflag",
                                                      "collection_id": "voidPlus_ValidationFlag",
                                                      "label": "ValidationFlag"},
                            {"collection": "bredius_schema_place", "collection_id": "schema_Place", "label": "Place"},
                            {"collection": "bredius_voidplus_linksetformulation",
                             "collection_id": "voidPlus_LinksetFormulation", "label": "LinksetFormulation"},
                            {"collection": "bredius_voidplus_matchingmethod",
                             "collection_id": "voidPlus_MatchingMethod", "label": "MatchingMethod"},
                            {"collection": "bredius_voidplus_resourceselection",
                             "collection_id": "voidPlus_ResourceSelection", "label": "ResourceSelection"},
                            {"collection": "bredius_voidplus_classpartition",
                             "collection_id": "voidPlus_ClassPartition", "label": "ClassPartition"},
                            {"collection": "bredius_schema_role", "collection_id": "schema_Role", "label": "Role"},
                            {"collection": "bredius_schema_manuscript", "collection_id": "schema_Manuscript",
                             "label": "Manuscript"},
                            {"collection": "bredius_schema_definedterm", "collection_id": "schema_DefinedTerm",
                             "label": "DefinedTerm"},
                            {"collection": "bredius_schema_creativework", "collection_id": "schema_CreativeWork",
                             "label": "CreativeWork"}, {"collection": "bredius_voidplus_propertypartition",
                                                        "collection_id": "voidPlus_PropertyPartition",
                                                        "label": "PropertyPartition"},
                            {"collection": "bredius_void_dataset", "collection_id": "void_Dataset", "label": "Dataset"},
                            {"collection": "bredius_schema_organization", "collection_id": "schema_Organization",
                             "label": "Organization"}, {"collection": "bredius_schema_archivecomponent",
                                                        "collection_id": "schema_ArchiveComponent",
                                                        "label": "ArchiveComponent"},
                            {"collection": "bredius_voidplus_cluster", "collection_id": "voidPlus_Cluster",
                             "label": "Cluster"}, {"collection": "bredius_voidplus_matchingalgorithm",
                                                   "collection_id": "voidPlus_MatchingAlgorithm",
                                                   "label": "MatchingAlgorithm"},
                            {"collection": "bredius_voidplus_linkset", "collection_id": "voidPlus_Linkset",
                             "label": "Linkset"},
                            {"collection": "bredius_schema_person", "collection_id": "schema_Person",
                             "label": "Person"},
                            {"collection": "bredius_rdfs_resource", "collection_id": "rdfs_Resource",
                             "label": "Resource"}]
            },
            {
                "dataSet": "u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__stcn",
                "label": "Koninklijke Bibliotheek: STCN",
                "indexes": [
                    {"collection": "stcn_schema_postaladdress", "collection_id": "schema_PostalAddress",
                     "label": "PostalAddress"},
                    {"collection": "stcn_schema_book", "collection_id": "schema_Book", "label": "Book"},
                    {"collection": "stcn_schema_webpage", "collection_id": "schema_WebPage", "label": "WebPage"},
                    {"collection": "stcn_schema_role", "collection_id": "schema_Role", "label": "Role"},
                    {"collection": "stcn_schema_governmentorganization",
                     "collection_id": "schema_GovernmentOrganization", "label": "GovernmentOrganization"},
                    {"collection": "stcn_schema_individualproduct", "collection_id": "schema_IndividualProduct",
                     "label": "IndividualProduct"},
                    {"collection": "stcn_ns3_fictionalplace", "collection_id": "ns3_FictionalPlace",
                     "label": "FictionalPlace"},
                    {"collection": "stcn_rdfs_class", "collection_id": "rdfs_Class", "label": "Class"},
                    {"collection": "stcn_schema_creativework", "collection_id": "schema_CreativeWork",
                     "label": "CreativeWork"},
                    {"collection": "stcn_schema_place", "collection_id": "schema_Place", "label": "Place"},
                    {"collection": "stcn_schema_organization", "collection_id": "schema_Organization",
                     "label": "Organization"},
                    {"collection": "stcn_skos_concept", "collection_id": "skos_Concept", "label": "Concept"},
                    {"collection": "stcn_https___w3id_org_pnv_personname",
                     "collection_id": "https___w3id_org_pnv_PersonName", "label": "PersonName"},
                    {"collection": "stcn_schema_dataset", "collection_id": "schema_Dataset", "label": "Dataset"},
                    {"collection": "stcn_schema_publicationvolume", "collection_id": "schema_PublicationVolume",
                     "label": "PublicationVolume"},
                    {"collection": "stcn_rdfs_resource", "collection_id": "rdfs_Resource", "label": "Resource"},
                    {"collection": "stcn_schema_productmodel", "collection_id": "schema_ProductModel",
                     "label": "ProductModel"}
                ]
            }
        ]}
        return store
