import json


class Store:

    def get_data(self):
        store = {"dataSets": [
            {
                "dataSet": "u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__jaikwil",
                "label": "Ja, ik wil!",
                "indexes": [
                    {"collection": "jaikwil_thes_bruidegom", "collection_id": "thes_Bruidegom", "label": "Bruidegom"},
                    {"collection": "jaikwil_rpp_occupation", "collection_id": "rpp_Occupation", "label": "Occupation"},
                    {"collection": "jaikwil_thes_eerdereman", "collection_id": "thes_EerdereMan",
                     "label": "EerdereMan"},
                    {"collection": "jaikwil_ns1_place", "collection_id": "ns1_Place", "label": "Place"},
                    {"collection": "jaikwil_thes_bruid", "collection_id": "thes_Bruid", "label": "Bruid"},
                    {"collection": "jaikwil_thes_persoonsreligie", "collection_id": "thes_Persoonsreligie",
                     "label": "Persoonsreligie"},
                    {"collection": "jaikwil_thes_herkomstlocatie", "collection_id": "thes_Herkomstlocatie",
                     "label": "Herkomstlocatie"},
                    {"collection": "jaikwil_skos_concept", "collection_id": "skos_Concept", "label": "Concept"},
                    {"collection": "jaikwil_pnv_personname", "collection_id": "pnv_PersonName", "label": "PersonName"},
                    {"collection": "jaikwil_rpp_location", "collection_id": "rpp_Location", "label": "Location"},
                    {"collection": "jaikwil_rpp_observation", "collection_id": "rpp_Observation",
                     "label": "Observation"},
                    {"collection": "jaikwil_thes_eerderevrouw", "collection_id": "thes_EerdereVrouw",
                     "label": "EerdereVrouw"},
                    {"collection": "jaikwil_rpp_indexdocument", "collection_id": "rpp_IndexDocument",
                     "label": "IndexDocument"},
                    {"collection": "jaikwil_ns1_occupation", "collection_id": "ns1_Occupation", "label": "Occupation"},
                    {"collection": "jaikwil_thes_ondertrouwregister", "collection_id": "thes_Ondertrouwregister",
                     "label": "Ondertrouwregister"},
                    {"collection": "jaikwil_thes_huwelijksestaat", "collection_id": "thes_Huwelijksestaat",
                     "label": "Huwelijksestaat"},
                    {"collection": "jaikwil_rpp_religion", "collection_id": "rpp_Religion", "label": "Religion"},
                    {"collection": "jaikwil_rpp_reconstruction", "collection_id": "rpp_Reconstruction",
                     "label": "Reconstruction"},
                    {"collection": "jaikwil_rpp_relation", "collection_id": "rpp_Relation", "label": "Relation"},
                    {"collection": "jaikwil_thes_relatieomschrijving", "collection_id": "thes_Relatieomschrijving",
                     "label": "Relatieomschrijving"},
                    {"collection": "jaikwil_thes_beroep", "collection_id": "thes_Beroep", "label": "Beroep"},
                    {"collection": "jaikwil_thes_getuige", "collection_id": "thes_Getuige", "label": "Getuige"},
                    {"collection": "jaikwil_rdfs_resource", "collection_id": "rdfs_Resource", "label": "Resource"},
                    {"collection": "jaikwil_thes_adresomschrijving", "collection_id": "thes_Adresomschrijving",
                     "label": "Adresomschrijving"},
                    {"collection": "jaikwil_rpp_person", "collection_id": "rpp_Person", "label": "Person"}
                ]
            },
            {
                "dataSet": "u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__notarissennetwerk",
                "label": "Notarissennetwerk",
                "indexes": [
                    {"collection": "notarissennetwerk_bio_divorce", "collection_id": "bio_Divorce", "label": "Divorce"},
                    {"collection": "notarissennetwerk_schema_postaladdress", "collection_id": "schema_PostalAddress",
                     "label": "PostalAddress"},
                    {"collection": "notarissennetwerk_schema_book", "collection_id": "schema_Book", "label": "Book"},
                    {"collection": "notarissennetwerk_sem_eventtype", "collection_id": "sem_EventType",
                     "label": "EventType"},
                    {"collection": "notarissennetwerk_schema_role", "collection_id": "schema_Role", "label": "Role"},
                    {"collection": "notarissennetwerk_bio_marriage", "collection_id": "bio_Marriage",
                     "label": "Marriage"},
                    {"collection": "notarissennetwerk_bio_burial", "collection_id": "bio_Burial", "label": "Burial"},
                    {"collection": "notarissennetwerk_schema_creativework", "collection_id": "schema_CreativeWork",
                     "label": "CreativeWork"},
                    {"collection": "notarissennetwerk_schema_occupation", "collection_id": "schema_Occupation",
                     "label": "Occupation"},
                    {"collection": "notarissennetwerk_bio_death", "collection_id": "bio_Death", "label": "Death"},
                    {"collection": "notarissennetwerk_bio_individualevent", "collection_id": "bio_IndividualEvent",
                     "label": "IndividualEvent"},
                    {"collection": "notarissennetwerk_schema_place", "collection_id": "schema_Place", "label": "Place"},
                    {"collection": "notarissennetwerk_schema_propertyvalue", "collection_id": "schema_PropertyValue",
                     "label": "PropertyValue"},
                    {"collection": "notarissennetwerk_schema_visualartwork", "collection_id": "schema_VisualArtwork",
                     "label": "VisualArtwork"},
                    {"collection": "notarissennetwerk_bio_baptism", "collection_id": "bio_Baptism", "label": "Baptism"},
                    {"collection": "notarissennetwerk_sem_event", "collection_id": "sem_Event", "label": "Event"},
                    {"collection": "notarissennetwerk_pnv_personname", "collection_id": "pnv_PersonName",
                     "label": "PersonName"},
                    {
                        "collection": "notarissennetwerk_https___data_goldenagents_org_datasets_saa_ontology_intendedmarriage",
                        "collection_id": "https___data_goldenagents_org_datasets_SAA_ontology_IntendedMarriage",
                        "label": "IntendedMarriage"},
                    {"collection": "notarissennetwerk_bio_resignation", "collection_id": "bio_Resignation",
                     "label": "Resignation"},
                    {"collection": "notarissennetwerk_schema_person", "collection_id": "schema_Person",
                     "label": "Person"},
                    {"collection": "notarissennetwerk_rdfs_resource", "collection_id": "rdfs_Resource",
                     "label": "Resource"},
                    {"collection": "notarissennetwerk_bio_birth", "collection_id": "bio_Birth", "label": "Birth"}
                ]
            },
            {
                "dataSet": "u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__rijksmuseum",
                "label": "Rijksmuseum",
                "indexes": [
                    {"collection": "rijksmuseum_http___www_openarchives_org_ore_terms_aggregation",
                     "collection_id": "http___www_openarchives_org_ore_terms_Aggregation", "label": "Aggregation"},
                    {"collection": "rijksmuseum_http___rdfs_org_ns_void_dataset",
                     "collection_id": "http___rdfs_org_ns_void_Dataset", "label": "Dataset"},
                    {"collection": "rijksmuseum_skos_concept", "collection_id": "skos_Concept", "label": "Concept"},
                    {"collection": "rijksmuseum_edm_place", "collection_id": "edm_Place", "label": "Place"},
                    {"collection": "rijksmuseum_edm_webresource", "collection_id": "edm_WebResource",
                     "label": "WebResource"},
                    {"collection": "rijksmuseum_edm_agent", "collection_id": "edm_Agent", "label": "Agent"},
                    {"collection": "rijksmuseum_edm_timespan", "collection_id": "edm_TimeSpan", "label": "TimeSpan"},
                    {"collection": "rijksmuseum_edm_providedcho", "collection_id": "edm_ProvidedCHO",
                     "label": "ProvidedCHO"},
                    {"collection": "rijksmuseum_rdfs_resource", "collection_id": "rdfs_Resource", "label": "Resource"}
                ]
            },
            {
                "dataSet": "u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__schrijverskabinet",
                "label": "Schrijverskabinet",
                "indexes": [
                    {"collection": "schrijverskabinet_schema_scholarlyarticle",
                     "collection_id": "schema_ScholarlyArticle", "label": "ScholarlyArticle"},
                    {"collection": "schrijverskabinet_schema_visualartwork", "collection_id": "schema_VisualArtwork",
                     "label": "VisualArtwork"},
                    {"collection": "schrijverskabinet_schema_creativework", "collection_id": "schema_CreativeWork",
                     "label": "CreativeWork"},
                    {"collection": "schrijverskabinet_schema_person", "collection_id": "schema_Person",
                     "label": "Person"},
                    {"collection": "schrijverskabinet_schema_place", "collection_id": "schema_Place", "label": "Place"},
                    {"collection": "schrijverskabinet_rdfs_resource", "collection_id": "rdfs_Resource",
                     "label": "Resource"},
                    {"collection": "schrijverskabinet_schema_publicationevent",
                     "collection_id": "schema_PublicationEvent", "label": "PublicationEvent"}
                ]
            },
            {
                "dataSet": "u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__stcn",
                "label": "Koninklijke Bibliotheek: STCN",
                "indexes": [
                    {"collection": "stcn_schema_postaladdress", "collection_id": "schema_PostalAddress",
                     "label": "PostalAddress"},
                    {"collection": "stcn_schema_book", "collection_id": "schema_Book", "label": "Book"},
                    {"collection": "stcn_schema_webpage", "collection_id": "schema_WebPage", "label": "WebPage"},
                    {"collection": "stcn_schema_role", "collection_id": "schema_Role", "label": "Role"},
                    {"collection": "stcn_schema_governmentorganization",
                     "collection_id": "schema_GovernmentOrganization", "label": "GovernmentOrganization"},
                    {"collection": "stcn_schema_individualproduct", "collection_id": "schema_IndividualProduct",
                     "label": "IndividualProduct"},
                    {"collection": "stcn_ns3_fictionalplace", "collection_id": "ns3_FictionalPlace",
                     "label": "FictionalPlace"},
                    {"collection": "stcn_rdfs_class", "collection_id": "rdfs_Class", "label": "Class"},
                    {"collection": "stcn_schema_creativework", "collection_id": "schema_CreativeWork",
                     "label": "CreativeWork"},
                    {"collection": "stcn_schema_place", "collection_id": "schema_Place", "label": "Place"},
                    {"collection": "stcn_schema_organization", "collection_id": "schema_Organization",
                     "label": "Organization"},
                    {"collection": "stcn_skos_concept", "collection_id": "skos_Concept", "label": "Concept"},
                    {"collection": "stcn_https___w3id_org_pnv_personname",
                     "collection_id": "https___w3id_org_pnv_PersonName", "label": "PersonName"},
                    {"collection": "stcn_schema_dataset", "collection_id": "schema_Dataset", "label": "Dataset"},
                    {"collection": "stcn_schema_publicationvolume", "collection_id": "schema_PublicationVolume",
                     "label": "PublicationVolume"},
                    {"collection": "stcn_rdfs_resource", "collection_id": "rdfs_Resource", "label": "Resource"},
                    {"collection": "stcn_schema_productmodel", "collection_id": "schema_ProductModel",
                     "label": "ProductModel"}
                ]
            }
        ]}
        return store
